### ISSUE TITLE
"Open" to show more results not obvious

### ISSUE THREAD

**Issue by digitalcircuit** [justjanne/quassel-rest-search#17]
The `Open` button on the far-right of a buffer's search result seems easy enough to miss, not having any obvious connection with "more results might exist."

Maybe `Show More Results` should somehow be visible without expanding?  Or some other indication that expanding the list of results may offer further results?

*I can expand upon this issue, try to add a mockup, etc, just making sure it's noted somewhere.*

**Comment by digitalcircuit** [comment]
The new update addresses pretty much everything!

My only concern would be indicating there's more already-loaded results hidden after you close the expanded view, e.g. if someone closes it while waiting for loading.  If the `Close` button remains the only way to close the expanded view, this might be unneeded.

**Comment by justjanne** [comment]
I was planning to add a loading indicator to the buffer itself. Once that’s disappeared, the user would know that the page had loaded.

**Comment by digitalcircuit** [comment]
Sounds good!  I'll go ahead and close this issue since loading indicators are a separate, known issue.
