### ISSUE TITLE
Login/Logout do not update userdata, requires page reload

### ISSUE THREAD

**Issue by digitalcircuit** [justjanne/quassel-rest-search#2]
The `Login` and `Logout` buttons [update local storage](https://github.com/justjanne/quassel-rest-search/blob/496809c5e36ad4b8c21aa0d6bbad05673a55aeb9/script.js#L33-L40), but do not update the [`userdata` object](https://github.com/justjanne/quassel-rest-search/blob/496809c5e36ad4b8c21aa0d6bbad05673a55aeb9/script.js#L1) referenced elsewhere in the script.

One potential fix: load `userdata` via a function, e.g. `loadSettings()`, then modify `$("#login").click(…)` and `$("#logout").click(…)` to call this function.

**Comment by justjanne** [comment]
Fixed in a later version
