### ISSUE TITLE
Failed authentication not shown via interface or when viewing API

### ISSUE THREAD

**Issue by digitalcircuit** [justjanne/quassel-rest-search#3]
Whenever performing a search, the web page doesn't warn if the username and password are empty or the authentication fails.  [`script.js` doesn't seem to make use of the response code](https://github.com/justjanne/quassel-rest-search/blob/496809c5e36ad4b8c21aa0d6bbad05673a55aeb9/script.js#L138-L148).

Likewise, should anyone try visiting the PHP files directly, the browser shoes a blank page without explanation (_asides from a note in the Network tab of Developer Tools_).  The calls to `backend.php`, [e.g. this reference in search.php](https://github.com/justjanne/quassel-rest-search/blob/496809c5e36ad4b8c21aa0d6bbad05673a55aeb9/search.php#L6-L10), should return a response of some sort, such as `HTTP 403: Unauthorized` or a JSON reply, e.g.

``` json
[{"error":"missing_user_pass"}]
```

_Other options usable, of course_

**Comment by justjanne** [comment]
Fixed in a later version
