### ISSUE TITLE
Show entire message when preview expanded

### ISSUE THREAD

**Issue by digitalcircuit** [justjanne/quassel-rest-search#5]
Currently, messages are truncated in two ways with no way to see the full message in the search interface.
1. Responses from `search.php`, using the [`ts_headline` SQL call in `backend.php`](https://github.com/justjanne/quassel-rest-search/blob/496809c5e36ad4b8c21aa0d6bbad05673a55aeb9/backend.php#L62)
   - When expanding the message preview, the full message is never updated, even though `context.php` returns the full message text when called to provide earlier and later messages
   - Formatting may need merged to preserve emphasis on the **highlighted words**
2. Full context messages that exceed the line width
   - Expand by default when viewing context of a particular conversation, or expand on a separate click
### Screenshot

![Message truncation in expanded view and tr_headlines](https://zorro.casa/go/db/Hosting/Utilities/Quassel/Quassel%20Rest%20Search/Development/issues/message-truncate/Message%20truncation%20in%20expanded%20view%20and%20tr_headlines.png#v7)

**Comment by justjanne** [comment]
Has been fixed already.
