### ISSUE TITLE
Additional buffer results won't show context, hidden when buffer collapsed

### ISSUE THREAD

**Issue by digitalcircuit** [justjanne/quassel-rest-search#6]
The behavior around `Load More Results` is inconsistent.  After loading more results, clicking on any of _new_ rows loaded will just collapse the buffer rather than showing context.  Perhaps something's amiss in [`attach_context`](https://github.com/justjanne/quassel-rest-search/blob/496809c5e36ad4b8c21aa0d6bbad05673a55aeb9/script.js#L113-L126)?

Once more results for a particular buffer have been loaded, clicking outside the buffer to collapse it provides no indication of additional messages loaded.  Perhaps `Load More Results` should change into `Show More Results` to re-expand the buffer list without sending any more queries, returning to `Load More Results` once expanded.

_Ubuntu Linux, Firefox 45.0 (mobile and desktop)_
### Loading context

![Load More Results context above but collapse below line](https://zorro.casa/go/db/Hosting/Utilities/Quassel/Quassel%20Rest%20Search/Development/issues/more-results-inconsistent/Load%20More%20Results%20context%20above%20but%20collapse%20below%20line.png#v2)
### Show More Results mockup

![Load More Results versus Show More Results](https://zorro.casa/go/db/Hosting/Utilities/Quassel/Quassel%20Rest%20Search/Development/issues/more-results-inconsistent/Load%20More%20Results%20versus%20Show%20More%20Results.png#v2)

**Comment by justjanne** [comment]
Fixed, and "show more results" solution implemented
